name = "ExampleApplication"
uuid = "7b1f14b7-3d46-40b7-b276-0ca587024dfa"
authors = ["Jared Wahlstrand <jwahlstrand@gmail.com>"]
version = "0.1.0"

[deps]
Gtk4 = "9db2cae5-386f-4011-9d63-a5602296539b"
